# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b050f0abdb617225779de449eb24b0ba4d27139b609e8448e7b61419dbd91060e87a6a2b516fcdec0d8c31bfba77427df1437aa0ee31ef35f91b8eb9abe9bd8a

test:
  secret_key_base: 089ca85898515ce06521f7b7113b62d54eec094a572ac49686d8d21494cd97f15dda76483a15f1752c0917eef1d4da22302ce63b0bb0813e1e27b05f8c32910d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
